case:
  linux:
    base: ./base/train_infer_with_gpu_base.yaml
    train:
      -
        name: dygraph
        cmd: python -u tools/trainer.py

    infer:
      -
        name: dygraph
        cmd: python -u tools/infer.py

  # mac:
  #   base: ./base/train_infer_with_cpu_base.yaml
  #   train:
  #     -
  #       name: dygraph
  #       cmd: python -u tools/trainer.py

  #   infer:
  #     -
  #       name: dygraph
  #       cmd: python -u tools/infer.py

  windows:
    base: ./base/train_infer_with_gpu_base.yaml
    train:
      -
        name: dygraph
        cmd: python -u tools/trainer.py

    infer:
      -
        name: dygraph
        cmd: python -u tools/infer.py
