case:
    linux:
        base: ./base/3d_base_pretrained.yaml
        eval:
          -
            name: pretrained
          -
            name: pretrained_bs1
        predict:
          -
            name: pretrained
            params:
              - --lidar_file datasets/KITTI/training/velodyne/000000.bin
              - --point_cloud_range 0 -19.84 -2.5 47.36 19.84 0.5
              - --voxel_size .16 .16 3
              - --max_points_in_voxel 100
              - --max_voxel_num 12000
