case:
    linux:
        base: ./base/3d_base_pretrained.yaml
        eval:
          -
            name: pretrained
          -
            name: pretrained_bs1
        export:
          -
            name: pretrained
            params:
              - --input_shape 64 1024
        predict:
          -
            name: pretrained
            params:
              - --lidar_file datasets/KITTI/training/velodyne/000000.bin
              - --img_mean 12.12,10.88,0.23,-1.04,0.21
              - --img_std 12.32,11.47,6.91,0.86,0.16
