MODEL: "PGNET" # 模型名
PRIORITY: P0
GIT:
  addr: $REPO_PaddleOCR
  path: $ROOT_PATH/PaddleOCR
  branch: $ocr_BRANCH

ENV:
  PADDLE_ON_MODEL_CE: $PADDLE_ON_MODEL_CE

VARIABLES:
  model_scripts_path: scripts/PGNET/ #脚本的路径
  model_log_path: log

EXEC:
  exec_cases: [TRAIN]
  exec_priority: [P0]
  exec_tag: [linux_dy_gpu1,linux_dy_gpu2]

#测试套
TRAIN: # 训练步骤
  -
    priority: P0  # dy_gpu1
    tag: linux_dy_gpu1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train_1card.sh

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 109.408752
        threshold: 20
        actived: True
        evaluation: "-"
    output: $ROOT_PATH/$model_log_path/e2e_r50_vd_pgnet_1card.log
  -
    priority: P0  # dy_gpu1
    tag: linux_dy_gpu2
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train_2card.sh

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 103.036285
        threshold: 20
        actived: True
        evaluation: "-"
    output: $ROOT_PATH/$model_log_path/e2e_r50_vd_pgnet_2card.log
