case:
  linux:
    base: ./base/normal_base.yml
    train:
      -
        name: multi
        cmd : python -m paddle.distributed.launch tools/train.py
        params:
          - TrainReader.batch_size=1
      -
        name: single
        cmd : python tools/train.py
        params:
          - TrainReader.batch_size=1
    eval:
      -
        name: pretrained
        cmd: python tools/eval.py
    infer:
      -
        name: pretrained
        cmd: python tools/infer.py
    export:
      -
        name: pretrained
        cmd: python tools/export_model.py
    predict:
      -
        name: python
        cmd: python deploy/python/infer.py
      -
        name: cpp
        cmd: ./deploy/cpp/build/main
  windows:
    base: ./base/normal_base.yml
    train:
      -
        name: single
        cmd : python tools/train.py
        params:
          - TrainReader.batch_size=1
    eval:
      -
        name: pretrained
        cmd: python tools/eval.py
    infer:
      -
        name: pretrained
        cmd: python tools/infer.py
    export:
      -
        name: pretrained
        cmd: python tools/export_model.py
    predict:
      -
        name: python
        cmd: python deploy/python/infer.py


function: paddlelas_imagenet_parse
