case:
  linux:
    base: ./base/normal_base.yml
    train:
      -
        name: multi
        cmd : python -m paddle.distributed.launch tools/train.py
        params:
          - TrainReader.batch_size=1
      -
        name: single
        cmd : python tools/train.py
        params:
          - TrainReader.batch_size=1
      -
        name: amp_multi
      -
        name: static_multi
    eval:
      -
        name: pretrained
        cmd: python tools/eval.py
    infer:
      -
        name: pretrained
        cmd: python tools/infer.py
    export:
      -
        name: pretrained
        cmd: python tools/export_model.py
    predict:
      -
        name: python
      -
        name: mkldnn
      -
        name: trt_fp32
      -
        name: trt_fp16
      -
        name: paddle2onnx
      -
        name: onnx_infer
    api: skipped
  windows:
    base: ./base/normal_base.yml
    train:
      -
        name: single
        cmd : python tools/train.py
        params:
          - TrainReader.batch_size=1
    eval:
      -
        name: pretrained
        cmd: python tools/eval.py
    infer:
      -
        name: pretrained
        cmd: python tools/infer.py
    export:
      -
        name: pretrained
        cmd: python tools/export_model.py
    predict:
      -
        name: python
        cmd: python deploy/python/infer.py
  mac:
    base: ./base/normal_base.yml
    train:
      -
        name: single
        cmd : python tools/train.py
        params:
          - TrainReader.batch_size=1
          - use_gpu=false
    eval:
      -
        name: pretrained
        cmd: python tools/eval.py
        params:
          - use_gpu=false
    infer:
      -
        name: pretrained
        cmd: python tools/infer.py
        params:
          - use_gpu=false
    export:
      -
        name: pretrained
        cmd: python tools/export_model.py
        params:
          - use_gpu=false
    predict:
      -
        name: python
        cmd: python deploy/python/infer.py
        params:
          - --device=CPU


function: paddlelas_imagenet_parse
