MODEL: "match_pyramid" # 模型名
PRIORITY: P1
GIT:
  addr: $REPO_PaddleRec
  path: $ROOT_PATH/PaddleRec
  branch: $match_pyramid_BRANCH

ENV:
  PADDLE_ON_MODEL_CE: $PADDLE_ON_MODEL_CE

VARIABLES:
  model_scripts_path: scripts/match_pyramid/ #脚本的路径
  model_log_path: log/match_pyramid/

EXEC:
  exec_cases: [DATA_PROC,TRAIN,INFER]
  exec_priority: [p1]
  exec_tag: $EXEC_TAG_LINUX_GPU2

#测试套
DATA_PROC:
  -
    tag: linux_down_data
    priority: p1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh data_proc.sh letor07

TRAIN: # 训练步骤
  -
    tag: linux_dy_gpu1 # dy_gpu1
    priority: p1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_dy_gpu1 match_pyramid_linux_dy_gpu1

    kpis: #kpi指标
      map:
        latest: True
        kpi_base: 0.39
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/S_match_pyramid_linux_dy_gpu1.log
  -
    tag: linux_dy_gpu2  # dy_gpu2
    priority: p1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_dy_gpu2 match_pyramid_linux_dy_gpu2

    kpis: #kpi指标
      map:
        latest: True
        kpi_base: 0.39
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/match_pyramid_linux_dy_gpu2_dist_log/workerlog.0
  -
    tag: linux_dy_cpu   # dy_cpu
    priority: p1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_dy_cpu match_pyramid_linux_dy_cpu

    kpis: #kpi指标
      map:
        latest: True
        kpi_base: 0.39
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/S_match_pyramid_linux_dy_cpu.log

  -
    tag: linux_st_gpu1  # st_gpu1
    priority: p1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_st_gpu1 match_pyramid_linux_st_gpu1

    kpis: #kpi指标
      map:
        latest: True
        kpi_base: 0.39
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/S_match_pyramid_linux_st_gpu1.log
  -
    tag: linux_st_gpu2  # st_gpu2
    priority: p1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_st_gpu2 match_pyramid_linux_st_gpu2

    kpis: #kpi指标
      map:
        latest: True
        kpi_base: 0.39
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/match_pyramid_linux_st_gpu2_dist_log/workerlog.0

  -
    tag: linux_st_cpu # st_cpu
    priority: p1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_st_cpu match_pyramid_linux_st_cpu

    kpis: #kpi指标
      map:
        latest: True
        kpi_base: 0.39
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/S_match_pyramid_linux_st_cpu.log


INFER:
  - #可以有多步
    tag: linux_dy_gpu1
    priority: p1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh infer.sh linux_dy_gpu1 match_pyramid_infer_linux_dy_gpu1

    kpis: #kpi指标
      map:
        latest: True
        kpi_base: 0.39
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/S_match_pyramid_infer_linux_dy_gpu1_eval.log
  -
    tag: linux_dy_gpu2
    priority: p1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh infer.sh linux_dy_gpu2 match_pyramid_infer_linux_dy_gpu2
    kpis: #kpi指标
      map:
        latest: True
        kpi_base: 0.39
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/S_match_pyramid_infer_linux_dy_gpu2_eval.log
  -
    tag: linux_dy_cpu
    priority: p1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh infer.sh linux_dy_cpu match_pyramid_infer_linux_dy_cpu

    kpis: #kpi指标
      map:
        latest: True
        kpi_base: 0.39
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/S_match_pyramid_infer_linux_dy_cpu_eval.log
  - #可以有多步
    tag: linux_st_gpu1
    priority: p1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh infer.sh linux_st_gpu1 match_pyramid_infer_linux_st_gpu1

    kpis: #kpi指标
      map:
        latest: True
        kpi_base: 0.39
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/S_match_pyramid_infer_linux_st_gpu1_eval.log
  -
    tag: linux_st_gpu2
    priority: p1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh infer.sh linux_st_gpu2 match_pyramid_infer_linux_st_gpu2

    kpis: #kpi指标
      map:
        latest: True
        kpi_base: 0.39
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/S_match_pyramid_infer_linux_st_gpu2_eval.log
  -
    tag: linux_st_cpu
    priority: p1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh infer.sh linux_st_cpu match_pyramid_infer_linux_st_cpu

    kpis: #kpi指标
      map:
        latest: True
        kpi_base: 0.39
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/S_match_pyramid_infer_linux_st_cpu_eval.log


