MODEL: "rank_fm" # 模型名
PRIORITY: P1
GIT:
  addr: $REPO_PaddleRec
  path: $ROOT_PATH/PaddleRec
  branch: $rank_fm_BRANCH

ENV:
  PADDLE_ON_MODEL_CE: $PADDLE_ON_MODEL_CE

VARIABLES:
  model_scripts_path: scripts/rank/ #脚本的路径
  model_log_path: log/rank_fm/

EXEC:
  exec_cases: [DATA_PROC,TRAIN,INFER]
  exec_priority: [p1]
  exec_tag: $EXEC_TAG_LINUX_GPU2

#测试套
DATA_PROC:
  -
    tag: linux_down_data
    priority: p1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh data_proc.sh criteo

TRAIN: # 训练步骤
  -
    tag: linux_dy_gpu1 # dy_gpu1
    priority: p1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_dy_gpu1 rank_fm_linux_dy_gpu1

    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.78
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/S_rank_fm_linux_dy_gpu1.log
  -
    tag: linux_dy_gpu2 # dy_gpu2
    priority: p1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_dy_gpu2 rank_fm_linux_dy_gpu2

    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.78
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/rank_fm_linux_dy_gpu2_dist_log/workerlog.0
  -
    tag: linux_dy_cpu # dy_cpu
    priority: p1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_dy_cpu rank_fm_linux_dy_cpu

    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.78
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/S_rank_fm_linux_dy_cpu.log

  -
    tag: linux_st_gpu1  # st_gpu1
    priority: p1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_st_gpu1 rank_fm_linux_st_gpu1

    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.78
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/S_rank_fm_linux_st_gpu1.log
  -
    tag: linux_st_gpu2  # st_gpu2
    priority: p1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_st_gpu2 rank_fm_linux_st_gpu2

    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.78
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/rank_fm_linux_st_gpu2_dist_log/workerlog.0

  -
    tag: linux_st_cpu  # st_cpu
    priority: p1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_st_cpu rank_fm_linux_st_cpu

    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.78
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/S_rank_fm_linux_st_cpu.log


INFER:
  - #可以有多步
    tag: linux_dy_gpu1
    priority: p1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh infer.sh linux_dy_gpu1 rank_fm_infer_linux_dy_gpu1

    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.78
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/S_rank_fm_infer_linux_dy_gpu1.log
  -
    tag: linux_dy_gpu2
    priority: p1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh infer.sh linux_dy_gpu2 rank_fm_infer_linux_dy_gpu2

    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.78
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/rank_fm_infer_linux_dy_gpu2_dist_log/workerlog.0
  -
    tag: linux_dy_cpu
    priority: p1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh infer.sh linux_dy_cpu rank_fm_infer_linux_dy_cpu

    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.78
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/S_rank_fm_infer_linux_dy_cpu.log
  - #可以有多步
    tag: linux_st_gpu1
    priority: p1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh infer.sh linux_st_gpu1 rank_fm_infer_linux_st_gpu1

    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.78
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/S_rank_fm_infer_linux_st_gpu1.log
  -
    tag: linux_st_gpu2
    priority: p1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh infer.sh linux_st_gpu2 rank_fm_infer_linux_st_gpu2

    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.78
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/rank_fm_infer_linux_st_gpu2_dist_log/workerlog.0
  -
    tag: linux_st_cpu
    priority: p1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh infer.sh linux_st_cpu rank_fm_infer_linux_st_cpu

    kpis: #kpi指标
      auc:
        latest: True
        kpi_base: 0.78
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/S_rank_fm_infer_linux_st_cpu.log


