MODEL: "rec_dy_dnn" # 模型名
PRIORITY: P2
GIT:
  addr: $REPO_PaddleRec
  path: $ROOT_PATH/PaddleRec
  branch: $rec_dy_dnn_BRANCH

ENV:
  PADDLE_ON_MODEL_CE: $PADDLE_ON_MODEL_CE

VARIABLES:
  model_scripts_path: scripts/rec_dy_dnn/ #脚本的路径
  model_log_path: log/rec_dy_dnn/

EXEC:
  exec_cases: [DATA_PROC,dy_TRAIN,dy_INFER]
  exec_priority: [p0]

#测试套
DATA_PROC:
  -
    priority: p0
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh data_proc.sh

dy_TRAIN: # 训练步骤
  -
    priority: p0
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh 'single' rank_dy_dnn_train_gpu1

    kpis: #kpi指标
      time:
        latest: True
        kpi_base: 182.4
        threshold: 0.02
        actived: True
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/S_rank_dy_dnn_train_gpu1.log

  -
    priority: p1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh 'multi' rank_dy_dnn_train_gpu2

    kpis: #kpi指标
      time:
        latest: True
        kpi_base: 182.4
        threshold: 0.02
        actived: True
        evaluation: "-"
        unit_repr: "s"

    output: $ROOT_PATH/$model_log_path/rank_dy_dnn_train_gpu2_dist_log/workerlog.0

  -
    priority: p2
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh 'cpu' rank_dy_dnn_train_cpu

    kpis: #kpi指标
      time:
        latest: True
        kpi_base: 182.4
        threshold: 0.02
        actived: True
        evaluation: "-"
        unit_repr: "s"

    output: $ROOT_PATH/$model_log_path/S_rank_dy_dnn_train_cpu.log

dy_INFER:
  - #可以有多步
    priority: p0
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh infer.sh 'single' rank_dy_dnn_infer_gpu1

    kpis: #kpi指标
      time:
        latest: True
        kpi_base: 182.4
        threshold: 0.02
        actived: True
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/S_rank_dy_dnn_infer_gpu1.log

  -
    priority: p1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh infer.sh 'cpu' rank_dy_dnn_infer_cpu

    kpis: #kpi指标
      time:
        latest: True
        kpi_base: 182.4
        threshold: 0.02
        actived: True
        evaluation: "-"
        unit_repr: "s"

    output: $ROOT_PATH/$model_log_path/S_rank_dy_dnn_infer_cpu.log