MODEL: "recall_ncf" # 模型名
PRIORITY: P0
GIT:
  addr: $REPO_PaddleRec
  path: $ROOT_PATH/PaddleRec
  branch: $rec_BRANCH

ENV:
  PADDLE_ON_MODEL_CE: $PADDLE_ON_MODEL_CE

VARIABLES:
  model_scripts_path: scripts/recall_ncf/ #脚本的路径
  model_log_path: log/recall_ncf/

EXEC:
  exec_cases: [DATA_PROC,TRAIN,INFER]
  exec_priority: [p0]
  exec_tag: $EXEC_TAG

#测试套
DATA_PROC:
  -
    tag: linux_down_data
    priority: p0
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh data_proc.sh movielens_pinterest_NCF

TRAIN: # 训练步骤
  -
    tag: linux_dy_gpu1  # dy_gpu1
    priority: p0
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_dy_gpu1 recall_ncf_linux_dy_gpu1

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 0.32776603
        threshold: 0.00000001
        actived: True
        evaluation: "-"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/S_recall_ncf_linux_dy_gpu1.log
  -
    tag: linux_dy_gpu2  # dy_gpu2
    priority: p0
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_dy_gpu2 recall_ncf_linux_dy_gpu2

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 0.3
        threshold: 0.03
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/S_recall_ncf_linux_dy_gpu2.log
  -
    tag: linux_dy_cpu   # dy_cpu
    priority: p0
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_dy_cpu recall_ncf_linux_dy_cpu

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 0.53728294
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/S_recall_ncf_linux_dy_cpu.log

  -
    tag: linux_st_gpu1  # st_gpu1
    priority: p0
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_st_gpu1 recall_ncf_linux_st_gpu1

    kpis: #kpi指标
      Loss:
        latest: True
        kpi_base: 0.3082
        threshold: 0.03
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/S_recall_ncf_linux_st_gpu1.log
  -
    tag: linux_st_gpu2  # st_gpu2
    priority: p0
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_st_gpu2 recall_ncf_linux_st_gpu2

    kpis: #kpi指标
      Loss:
        latest: True
        kpi_base: 0.3021
        threshold: 0.03
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/S_recall_ncf_linux_st_gpu2.log

  -
    tag: linux_st_cpu # st_cpu
    priority: p0
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_st_cpu recall_ncf_linux_st_cpu

    kpis: #kpi指标
      Loss:
        latest: True
        kpi_base: 0.53728294
        threshold: 0.001
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/S_recall_ncf_linux_st_cpu.log

  -
    tag: linux_dy_gpu1_con  # dy_gpu1
    priority: p0
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_dy_gpu1_con recall_ncf_linux_dy_gpu1_con

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 0.2121
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/S_recall_ncf_linux_dy_gpu1_con.log

  -
    tag: linux_st_gpu1_con  # dy_gpu1
    priority: p0
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh linux_st_gpu1_con recall_ncf_linux_st_gpu1_con

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 0.2121
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/S_recall_ncf_linux_st_gpu1_con.log
# mac train(small data)
  -
    tag: mac_dy_cpu
    priority: p0
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh mac_dy_cpu recall_ncf_mac_dy_cpu

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 0.5460826
        threshold: 0.001
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/S_recall_ncf_mac_dy_cpu.log
  -
    tag: mac_st_cpu
    priority: p0
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train.sh mac_st_cpu recall_ncf_mac_st_cpu

    kpis: #kpi指标
      Loss:
        latest: True
        kpi_base: 0.5460826
        threshold: 0.001
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/S_recall_ncf_mac_st_cpu.log
# win train(small data)
  -
    tag: win_dy_gpu
    priority: p0
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: train.bat win_dy_gpu recall_ncf_win_dy_gpu ncf

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 0.53728294
        threshold: 0.001
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/recall_ncf_win_dy_gpu.log
  -
    tag: win_dy_cpu
    priority: p0
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: train.bat win_dy_cpu recall_ncf_win_dy_cpu ncf

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 0.53728294
        threshold: 0.001
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/recall_ncf_win_dy_cpu.log
  -
    tag: win_st_gpu
    priority: p0
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: train.bat win_st_gpu recall_ncf_win_st_gpu ncf

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 0.53728294
        threshold: 0.001
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/recall_ncf_win_st_gpu.log
  -
    tag: win_st_cpu
    priority: p0
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: train.bat win_st_cpu recall_ncf_win_st_cpu ncf

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 0.53728294
        threshold: 0.001
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/recall_ncf_win_st_cpu.log

INFER:
  - #可以有多步
    tag: linux_dy_gpu1
    priority: p0
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh infer.sh linux_dy_gpu1 recall_ncf_infer_linux_dy_gpu1

    kpis: #kpi指标
      ndcg:
        latest: True
        kpi_base: 0.243253466
        threshold: 0.000000001
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/S_recall_ncf_infer_linux_dy_gpu1_evaluate.log
  -
    tag: linux_dy_gpu2
    priority: p0
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh infer.sh linux_dy_gpu2 recall_ncf_infer_linux_dy_gpu2
    kpis: #kpi指标
      ndcg:
        latest: True
        kpi_base: 0.24
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/S_recall_ncf_infer_linux_dy_gpu2_evaluate.log
  -
    tag: linux_dy_cpu
    priority: p0
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh infer.sh linux_dy_cpu recall_ncf_infer_linux_dy_cpu

    kpis: #kpi指标
      prediction:
        latest: True
        kpi_base: 0.34032416
        threshold: 0
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/S_recall_ncf_infer_linux_dy_cpu.log
  - #可以有多步
    tag: linux_st_gpu1
    priority: p0
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh infer.sh linux_st_gpu1 recall_ncf_infer_linux_st_gpu1

    kpis: #kpi指标
      ndcg:
        latest: True
        kpi_base: 0.24
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/S_recall_ncf_infer_linux_st_gpu1_evaluate.log
  -
    tag: linux_st_gpu2
    priority: p0
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh infer.sh linux_st_gpu2 recall_ncf_infer_linux_st_gpu2

    kpis: #kpi指标
      ndcg:
        latest: True
        kpi_base: 0.24
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/S_recall_ncf_infer_linux_st_gpu2_evaluate.log
  -
    tag: linux_st_cpu
    priority: p0
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh infer.sh linux_st_cpu recall_ncf_infer_linux_st_cpu

    kpis: #kpi指标
      prediction:
        latest: True
        kpi_base: [0.34032416]
        threshold: 0.001
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/S_recall_ncf_infer_linux_st_cpu.log

  -
    tag: linux_dy_gpu1_con
    priority: p0
    run:
      - path: $ROOT_PATH/$model_scripts_path
        cmd: sh infer.sh linux_dy_gpu1_con recall_ncf_infer_linux_dy_gpu1_con

    kpis: #kpi指标
      ndcg:
        latest: True
        kpi_base: 0.33
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/S_recall_ncf_infer_linux_dy_gpu1_con_evaluate.log

  -
    tag: linux_st_gpu1_con
    priority: p0
    run:
      - path: $ROOT_PATH/$model_scripts_path
        cmd: sh infer.sh linux_st_gpu1_con recall_ncf_infer_linux_st_gpu1_con

    kpis: #kpi指标
      ndcg:
        latest: True
        kpi_base: 0.33
        threshold: 0.02
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/S_recall_ncf_infer_linux_st_gpu1_con_evaluate.log
# mac infer(small data)
  -
    tag: mac_dy_cpu
    priority: p0
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh infer.sh mac_dy_cpu recall_ncf_infer_mac_dy_cpu

    kpis: #kpi指标
      prediction:
        latest: True
        kpi_base: 0.3516687
        threshold: 0.001
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/S_recall_ncf_infer_mac_dy_cpu.log
  -
    tag: mac_st_cpu
    priority: p0
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh infer.sh mac_st_cpu recall_ncf_infer_mac_st_cpu

    kpis: #kpi指标
      prediction:
        latest: True
        kpi_base: [0.3516687]
        threshold: 0.001
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/S_recall_ncf_infer_mac_st_cpu.log
# win infer(small data)
  -
    tag: win_dy_gpu
    priority: p0
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: infer.bat win_dy_gpu recall_ncf_infer_win_dy_gpu ncf

    kpis: #kpi指标
      prediction:
        latest: True
        kpi_base: 0.34032416
        threshold: 0.001
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/recall_ncf_infer_win_dy_gpu.log
  -
    tag: win_dy_cpu
    priority: p0
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: infer.bat win_dy_cpu recall_ncf_infer_win_dy_cpu ncf

    kpis: #kpi指标
      prediction:
        latest: True
        kpi_base: 0.34032416
        threshold: 0.001
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/recall_ncf_infer_win_dy_cpu.log
  -
    tag: win_st_gpu
    priority: p0
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: infer.bat win_st_gpu recall_ncf_infer_win_st_gpu ncf

    kpis: #kpi指标
      prediction:
        latest: True
        kpi_base: 0.34032416
        threshold: 0.001
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/recall_ncf_infer_win_st_gpu.log
  -
    tag: win_st_cpu
    priority: p0
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: infer.bat win_st_cpu recall_ncf_infer_win_st_cpu ncf

    kpis: #kpi指标
      prediction:
        latest: True
        kpi_base: 0.34032416
        threshold: 0.001
        actived: True
        evaluation: "+"
        unit_repr: None
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None

    output: $ROOT_PATH/$model_log_path/recall_ncf_infer_win_st_cpu.log
