MODEL: "DLA46_c" # 模型名
PRIORITY: P1
GIT:
  addr: $REPO_PaddleClas
  path: $ROOT_PATH/PaddleClas
  branch: $cls_BRANCH

ENV:
  PADDLE_ON_MODEL_CE: $PADDLE_ON_MODEL_CE

VARIABLES:
  model_function_path_linux: linux/ #脚本的路径
  model_function_path_win: windows/ #脚本的路径
  model_scripts_path: scripts/ #脚本的路径
  model_log_path: log

EXEC:
  exec_cases: [FUNCTION,TRAIN,EVAL,INFER,EXPORT,PREDICT]
  exec_priority: [P1]
  exec_tag: $EXEC_TAG

#测试套
FUNCTION: # 训练步骤
  -
    tag: linux_function_test
    priority: P1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置
    run:
      -
        path: $ROOT_PATH/$model_function_path_linux
        cmd: bash PaddleClas_CI_develop.sh ppcls/configs/ImageNet/DLA/DLA46_c.yaml
  -
    tag: win_function_test
    priority: P1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: None  #取值为None，则不设置
    run:
      -
        path: $ROOT_PATH/$model_function_path_win
        cmd: PaddleClas_train_gpu.bat ppcls/configs/ImageNet/DLA/DLA46_c.yaml

TRAIN: # 训练步骤
  -
    tag: train_linux_gpu1
    priority: P1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash grep_linux_log.sh ppcls/configs/ImageNet/DLA/DLA46_c.yaml train_linux_gpu1
    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 6.46143
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/DLA46_c_1card.log
  -
    tag: train_linux_gpu2
    priority: P1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash grep_linux_log.sh ppcls/configs/ImageNet/DLA/DLA46_c.yaml train_linux_gpu2
    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 6.22272
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/DLA46_c_2card.log
  -
    tag: train_win_gpu
    priority: P1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: grep_win_log.bat ppcls/configs/ImageNet/DLA/DLA46_c.yaml train_win_gpu
    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 6.80237
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/DLA46_c_train.log

EVAL: # 训练步骤
  -
    tag: eval_linux
    priority: P1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash grep_linux_log.sh ppcls/configs/ImageNet/DLA/DLA46_c.yaml eval_linux
    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 6.22272
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/DLA46_c_eval.log
  -
    tag: eval_win
    priority: P1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: grep_win_log.bat ppcls/configs/ImageNet/DLA/DLA46_c.yaml eval_win
    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 6.80237
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/DLA46_c_eval.log

INFER: # 训练步骤
  -
    tag: infer_linux
    priority: P1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash grep_linux_log.sh ppcls/configs/ImageNet/DLA/DLA46_c.yaml infer_linux
    kpis: #kpi指标
      infer_exit_code:
        latest: True
        kpi_base: 0.0
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/DLA46_c_infer.log
  -
    tag: infer_win
    priority: P1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: grep_win_log.bat ppcls/configs/ImageNet/DLA/DLA46_c.yaml infer_win
    kpis: #kpi指标
      infer_exit_code:
        latest: True
        kpi_base: 0.0
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/DLA46_c_infer.log

PREDICT: # 训练步骤
  -
    tag: predict_linux
    priority: P1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash grep_linux_log.sh ppcls/configs/ImageNet/DLA/DLA46_c.yaml predict_linux
    kpis: #kpi指标
      predict_exit_code:
        latest: True
        kpi_base: 0.0
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/DLA46_c_predict.log
  -
    tag: predict_win
    priority: P1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash grep_linux_log.sh ppcls/configs/ImageNet/DLA/DLA46_c.yaml predict_win
    kpis: #kpi指标
      predict_exit_code:
        latest: True
        kpi_base: 0.0
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/DLA46_c_predict.log