MODEL: "InceptionV4" # 模型名
PRIORITY: P0
GIT:
  addr: $REPO_PaddleClas
  path: $ROOT_PATH/PaddleClas
  branch: $cls_BRANCH

ENV:
  PADDLE_ON_MODEL_CE: $PADDLE_ON_MODEL_CE

VARIABLES:
  model_function_path: linux/ #脚本的路径
  model_scripts_path: scripts/ #脚本的路径
  model_log_path: log

EXEC:
  exec_cases: [FUNCTION,TRAIN,EVAL,INFER,EXPORT,PREDICT]
  exec_priority: [P0]
  exec_tag: [function_test,train_linux_gpu1,train_linux_gpu2,infer_linux,eval_linux,infer_linux,predict_linux]

#测试套
FUNCTION: # 训练步骤
  -
    tag: function_test
    priority: P0
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置
    run:
      -
        path: $ROOT_PATH/$model_function_path
        cmd: sh PaddleClas_CI_develop.sh ppcls/configs/ImageNet/Inception/InceptionV4.yaml
    kpis: #kpi指标
      training_multi_exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None
      training_single_exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None
      eval_exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None
      infer_exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None
      export_model_exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None
      predict_exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/PaddleClas/log/result.log

TRAIN: # 训练步骤
  -
    tag: train_linux_gpu1
    priority: P0
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh grep_linux_log.sh ppcls/configs/ImageNet/Inception/InceptionV4.yaml train_linux_gpu1
    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 6.42081
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/InceptionV4_1card.log
  -
    tag: train_linux_gpu2
    priority: P0
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh grep_linux_log.sh ppcls/configs/ImageNet/Inception/InceptionV4.yaml train_linux_gpu2
    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 6.31414
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/InceptionV4_2card.log

EVAL: # 训练步骤
  -
    tag: eval_linux
    priority: P0
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh grep_linux_log.sh ppcls/configs/ImageNet/Inception/InceptionV4.yaml eval_linux
    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 100
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/InceptionV4_eval.log

INFER: # 训练步骤
  -
    tag: infer_linux
    priority: P0
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh grep_linux_log.sh ppcls/configs/ImageNet/Inception/InceptionV4.yaml infer_linux
    kpis: #kpi指标
      infer_exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/InceptionV4_infer.log

PREDICT: # 训练步骤
  -
    tag: predict_linux
    priority: P0
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh grep_linux_log.sh ppcls/configs/ImageNet/Inception/InceptionV4.yaml predict_linux
    kpis: #kpi指标
      predict_exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/InceptionV4_predict.log
