MODEL: "MixNet_M" # 模型名
PRIORITY: P1,convergence_MixNet_M,MixNet_M
GIT:
  addr: $REPO_PaddleClas
  path: $ROOT_PATH/PaddleClas
  branch: $cls_BRANCH

ENV:
  PADDLE_ON_MODEL_CE: $PADDLE_ON_MODEL_CE

VARIABLES:
  model_function_path_linux: linux/ #脚本的路径
  model_function_path_win: windows/ #脚本的路径
  model_function_path_mac: mac/ #脚本的路径
  model_scripts_path: scripts/ #脚本的路径
  model_log_path: log

EXEC:
  exec_cases: [FUNCTION,TRAIN,EVAL,INFER,EXPORT,PREDICT]
  exec_priority: [P1]
  exec_tag: $EXEC_TAG

#测试套
FUNCTION: # 训练步骤
  -
    tag: linux_function_test
    priority: P1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置
    run:
      -
        path: $ROOT_PATH/$model_function_path_linux
        cmd: bash PaddleClas_CI_develop.sh ppcls/configs/ImageNet/MixNet/MixNet_M.yaml
  -
    tag: win_function_test
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_function_path_win
        cmd: PaddleClas_train_gpu.bat ppcls/configs/ImageNet/MixNet/MixNet_M.yaml
  -
    tag: win_cpu_function_test
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_function_path_win
        cmd: PaddleClas_train_cpu.bat ppcls/configs/ImageNet/MixNet/MixNet_M.yaml
  -
    tag: mac_function_test
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_function_path_mac
        cmd: bash PaddleClas_train_cpu.sh ppcls/configs/ImageNet/MixNet/MixNet_M.yaml
  -
    tag: linux_convergence_test
    priority: P1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置
    run:
      -
        path: $ROOT_PATH/$model_function_path_linux
        cmd: bash PaddleClas_convergence_develop.sh ppcls/configs/ImageNet/MixNet/MixNet_M.yaml

TRAIN: # 训练步骤
  -
    tag: train_linux_convergence
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash grep_linux_log.sh ppcls/configs/ImageNet/MixNet/MixNet_M.yaml train_linux_convergence
    kpis: #kpi指标
      metric:
        latest: True
        kpi_base: 0.512
        threshold: 0.1
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/MixNet_M_convergence.log
  -
    tag: train_linux_gpu1
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash grep_linux_log.sh ppcls/configs/ImageNet/MixNet/MixNet_M.yaml train_linux_gpu1
    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 6.49278
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
      train_eval:
        latest: True
        kpi_base: 12.25185
        threshold: 0.00001
        actived: True
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/MixNet_M_1card.log
  -
    tag: train_linux_gpu2
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash grep_linux_log.sh ppcls/configs/ImageNet/MixNet/MixNet_M.yaml train_linux_gpu2
    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 6.53958
        threshold: 0.0
        actived: True
        evaluation: "-"
        unit_repr: None
      train_eval:
        latest: True
        kpi_base: 7.01511
        threshold: 0.00001
        actived: True
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/MixNet_M_2card.log
  -
    tag: train_linux_gpu1_release
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash grep_linux_log.sh ppcls/configs/ImageNet/MixNet/MixNet_M.yaml train_linux_gpu1
    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 6.61655
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
      train_eval:
        latest: True
        kpi_base: 7.1193
        threshold: 0.00001
        actived: True
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/MixNet_M_1card.log
  -
    tag: train_linux_gpu2_release
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash grep_linux_log.sh ppcls/configs/ImageNet/MixNet/MixNet_M.yaml train_linux_gpu2
    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 6.52804
        threshold: 0.0
        actived: True
        evaluation: "-"
        unit_repr: None
      train_eval:
        latest: True
        kpi_base: 7.05802
        threshold: 0.00001
        actived: True
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/MixNet_M_2card.log
  -
    tag: train_win_gpu
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: grep_win_log.bat ppcls/configs/ImageNet/MixNet/MixNet_M.yaml train_win_gpu
    kpis: #kpi指标
      training_exit_code:
        latest: True
        kpi_base: 0.0
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/MixNet_M_train.log
  -
    tag: train_win_cpu
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: grep_win_log.bat ppcls/configs/ImageNet/MixNet/MixNet_M.yaml train_win_cpu
    kpis: #kpi指标
      training_exit_code:
        latest: True
        kpi_base: 0.0
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/MixNet_M_train.log
  -
    tag: train_mac_cpu
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash grep_mac_log.sh ppcls/configs/ImageNet/MixNet/MixNet_M.yaml train_mac_cpu
    kpis: #kpi指标
      training_exit_code:
        latest: True
        kpi_base: 0.0
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/MixNet_M_cpu.log

EVAL: # 训练步骤
  -
    tag: eval_linux
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash grep_linux_log.sh ppcls/configs/ImageNet/MixNet/MixNet_M.yaml eval_linux
    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 12.25185
        threshold: 0.00001
        actived: True
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/MixNet_M_eval.log
  -
    tag: eval_win
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: grep_win_log.bat ppcls/configs/ImageNet/MixNet/MixNet_M.yaml eval_win
    kpis: #kpi指标
      eval_exit_code:
        latest: True
        kpi_base: 0.0
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/MixNet_M_eval.log
  -
    tag: eval_mac
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash grep_mac_log.sh ppcls/configs/ImageNet/MixNet/MixNet_M.yaml eval_mac
    kpis: #kpi指标
      eval_exit_code:
        latest: True
        kpi_base: 0.0
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/MixNet_M_eval.log


INFER: # 训练步骤
  -
    tag: infer_linux
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash grep_linux_log.sh ppcls/configs/ImageNet/MixNet/MixNet_M.yaml infer_linux
    kpis: #kpi指标
      infer_exit_code:
        latest: True
        kpi_base: 0.0
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/MixNet_M_infer.log
  -
    tag: infer_win
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: grep_win_log.bat ppcls/configs/ImageNet/MixNet/MixNet_M.yaml infer_win
    kpis: #kpi指标
      infer_exit_code:
        latest: True
        kpi_base: 0.0
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/MixNet_M_infer.log
  -
    tag: infer_mac
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash grep_mac_log.sh ppcls/configs/ImageNet/MixNet/MixNet_M.yaml infer_mac
    kpis: #kpi指标
      infer_exit_code:
        latest: True
        kpi_base: 0.0
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/MixNet_M_infer.log

PREDICT: # 训练步骤
  -
    tag: predict_linux
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash grep_linux_log.sh ppcls/configs/ImageNet/MixNet/MixNet_M.yaml predict_linux
    kpis: #kpi指标
      predict_exit_code:
        latest: True
        kpi_base: 0.0
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/MixNet_M_predict.log
  -
    tag: predict_win
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: grep_win_log.bat ppcls/configs/ImageNet/MixNet/MixNet_M.yaml predict_win
    kpis: #kpi指标
      predict_exit_code:
        latest: True
        kpi_base: 0.0
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/MixNet_M_predict.log
  -
    tag: predict_mac
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash grep_mac_log.sh ppcls/configs/ImageNet/MixNet/MixNet_M.yaml predict_mac
    kpis: #kpi指标
      predict_exit_code:
        latest: True
        kpi_base: 0.0
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/MixNet_M_predict.log
