MODEL: "ResNeXt101_32x8d_wsl" # 模型名
PRIORITY: P1,convergence_ResNeXt101_32x8d_wsl,ResNeXt101_32x8d_wsl
GIT:
  addr: $REPO_PaddleClas
  path: $ROOT_PATH/PaddleClas
  branch: $cls_BRANCH

ENV:
  PADDLE_ON_MODEL_CE: $PADDLE_ON_MODEL_CE

VARIABLES:
  model_function_path_linux: linux/ #脚本的路径
  model_function_path_win: windows/ #脚本的路径
  model_function_path_mac: mac/ #脚本的路径
  model_scripts_path: scripts/ #脚本的路径
  model_log_path: log

EXEC:
  exec_cases: [FUNCTION,TRAIN,EVAL,INFER,EXPORT,PREDICT]
  exec_priority: [P1]
  exec_tag: $EXEC_TAG

#测试套
FUNCTION: # 训练步骤
  -
    tag: linux_function_test
    priority: P1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置
    run:
      -
        path: $ROOT_PATH/$model_function_path_linux
        cmd: bash PaddleClas_CI_develop.sh ppcls/configs/ImageNet/ResNeXt101_wsl/ResNeXt101_32x8d_wsl.yaml
  -
    tag: win_function_test
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_function_path_win
        cmd: PaddleClas_train_gpu.bat ppcls/configs/ImageNet/ResNeXt101_wsl/ResNeXt101_32x8d_wsl.yaml
  -
    tag: win_cpu_function_test
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_function_path_win
        cmd: PaddleClas_train_cpu.bat ppcls/configs/ImageNet/ResNeXt101_wsl/ResNeXt101_32x8d_wsl.yaml
  -
    tag: mac_function_test
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_function_path_mac
        cmd: bash PaddleClas_train_cpu.sh ppcls/configs/ImageNet/ResNeXt101_wsl/ResNeXt101_32x8d_wsl.yaml
  -
    tag: linux_convergence_test
    priority: P1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置
    run:
      -
        path: $ROOT_PATH/$model_function_path_linux
        cmd: bash PaddleClas_convergence_develop.sh ppcls/configs/ImageNet/ResNeXt101_wsl/ResNeXt101_32x8d_wsl.yaml

TRAIN: # 训练步骤
  -
    tag: train_linux_convergence
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash grep_linux_log.sh ppcls/configs/ImageNet/ResNeXt101_wsl/ResNeXt101_32x8d_wsl.yaml train_linux_convergence
    kpis: #kpi指标
      metric:
        latest: True
        kpi_base: 0.512
        threshold: 0.1
        actived: True
        evaluation: "+"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/ResNeXt101_32x8d_wsl_convergence.log
  -
    tag: train_linux_gpu1
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash grep_linux_log.sh ppcls/configs/ImageNet/ResNeXt101_wsl/ResNeXt101_32x8d_wsl.yaml train_linux_gpu1
    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 6.3635
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
      train_eval:
        latest: True
        kpi_base: 12.40129
        threshold: 0.00001
        actived: True
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/ResNeXt101_32x8d_wsl_1card.log
  -
    tag: train_linux_gpu2
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash grep_linux_log.sh ppcls/configs/ImageNet/ResNeXt101_wsl/ResNeXt101_32x8d_wsl.yaml train_linux_gpu2
    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 6.58852
        threshold: 0.0
        actived: True
        evaluation: "-"
        unit_repr: None
      train_eval:
        latest: True
        kpi_base: 7.01511
        threshold: 0.00001
        actived: True
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/ResNeXt101_32x8d_wsl_2card.log
  -
    tag: train_linux_gpu1_release
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash grep_linux_log.sh ppcls/configs/ImageNet/ResNeXt101_wsl/ResNeXt101_32x8d_wsl.yaml train_linux_gpu1
    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 6.44288
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
      train_eval:
        latest: True
        kpi_base: 18.24487
        threshold: 0.00001
        actived: True
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/ResNeXt101_32x8d_wsl_1card.log
  -
    tag: train_linux_gpu2_release
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash grep_linux_log.sh ppcls/configs/ImageNet/ResNeXt101_wsl/ResNeXt101_32x8d_wsl.yaml train_linux_gpu2
    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 6.49123
        threshold: 0.0
        actived: True
        evaluation: "-"
        unit_repr: None
      train_eval:
        latest: True
        kpi_base: 7.05802
        threshold: 0.00001
        actived: True
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/ResNeXt101_32x8d_wsl_2card.log
  -
    tag: train_win_gpu
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: grep_win_log.bat ppcls/configs/ImageNet/ResNeXt101_wsl/ResNeXt101_32x8d_wsl.yaml train_win_gpu
    kpis: #kpi指标
      training_exit_code:
        latest: True
        kpi_base: 0.0
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/ResNeXt101_32x8d_wsl_train.log
  -
    tag: train_win_cpu
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: grep_win_log.bat ppcls/configs/ImageNet/ResNeXt101_wsl/ResNeXt101_32x8d_wsl.yaml train_win_cpu
    kpis: #kpi指标
      training_exit_code:
        latest: True
        kpi_base: 0.0
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/ResNeXt101_32x8d_wsl_train.log
  -
    tag: train_mac_cpu
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash grep_mac_log.sh ppcls/configs/ImageNet/ResNeXt101_wsl/ResNeXt101_32x8d_wsl.yaml train_mac_cpu
    kpis: #kpi指标
      training_exit_code:
        latest: True
        kpi_base: 0.0
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/ResNeXt101_32x8d_wsl_cpu.log

EVAL: # 训练步骤
  -
    tag: eval_linux
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash grep_linux_log.sh ppcls/configs/ImageNet/ResNeXt101_wsl/ResNeXt101_32x8d_wsl.yaml eval_linux
    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 12.40129
        threshold: 0.00001
        actived: True
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/ResNeXt101_32x8d_wsl_eval.log
  -
    tag: eval_win
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: grep_win_log.bat ppcls/configs/ImageNet/ResNeXt101_wsl/ResNeXt101_32x8d_wsl.yaml eval_win
    kpis: #kpi指标
      eval_exit_code:
        latest: True
        kpi_base: 0.0
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/ResNeXt101_32x8d_wsl_eval.log
  -
    tag: eval_mac
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash grep_mac_log.sh ppcls/configs/ImageNet/ResNeXt101_wsl/ResNeXt101_32x8d_wsl.yaml eval_mac
    kpis: #kpi指标
      eval_exit_code:
        latest: True
        kpi_base: 0.0
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/ResNeXt101_32x8d_wsl_eval.log


INFER: # 训练步骤
  -
    tag: infer_linux
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash grep_linux_log.sh ppcls/configs/ImageNet/ResNeXt101_wsl/ResNeXt101_32x8d_wsl.yaml infer_linux
    kpis: #kpi指标
      infer_exit_code:
        latest: True
        kpi_base: 0.0
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/ResNeXt101_32x8d_wsl_infer.log
  -
    tag: infer_win
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: grep_win_log.bat ppcls/configs/ImageNet/ResNeXt101_wsl/ResNeXt101_32x8d_wsl.yaml infer_win
    kpis: #kpi指标
      infer_exit_code:
        latest: True
        kpi_base: 0.0
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/ResNeXt101_32x8d_wsl_infer.log
  -
    tag: infer_mac
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash grep_mac_log.sh ppcls/configs/ImageNet/ResNeXt101_wsl/ResNeXt101_32x8d_wsl.yaml infer_mac
    kpis: #kpi指标
      infer_exit_code:
        latest: True
        kpi_base: 0.0
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/ResNeXt101_32x8d_wsl_infer.log

PREDICT: # 训练步骤
  -
    tag: predict_linux
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash grep_linux_log.sh ppcls/configs/ImageNet/ResNeXt101_wsl/ResNeXt101_32x8d_wsl.yaml predict_linux
    kpis: #kpi指标
      predict_exit_code:
        latest: True
        kpi_base: 0.0
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/ResNeXt101_32x8d_wsl_predict.log
  -
    tag: predict_win
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: grep_win_log.bat ppcls/configs/ImageNet/ResNeXt101_wsl/ResNeXt101_32x8d_wsl.yaml predict_win
    kpis: #kpi指标
      predict_exit_code:
        latest: True
        kpi_base: 0.0
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/ResNeXt101_32x8d_wsl_predict.log
  -
    tag: predict_mac
    priority: P1
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash grep_mac_log.sh ppcls/configs/ImageNet/ResNeXt101_wsl/ResNeXt101_32x8d_wsl.yaml predict_mac
    kpis: #kpi指标
      predict_exit_code:
        latest: True
        kpi_base: 0.0
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/ResNeXt101_32x8d_wsl_predict.log
