MODEL: "ShuffleNetV2_x1_0" # 模型名
PRIORITY: P1
GIT:
  addr: $REPO_PaddleClas
  path: $ROOT_PATH/PaddleClas
  branch: $cls_BRANCH

ENV:
  PADDLE_ON_MODEL_CE: $PADDLE_ON_MODEL_CE

VARIABLES:
  model_function_path: linux/ #脚本的路径
  model_scripts_path: scripts/ #脚本的路径
  model_log_path: log

EXEC:
  exec_cases: [FUNCTION,TRAIN,EVAL,INFER,EXPORT,PREDICT]
  exec_priority: [P1]
  exec_tag: [function_test,train_linux_gpu1,train_linux_gpu2,eval_linux,infer_linux,predict_linux]

#测试套
FUNCTION: # 训练步骤
  -
    tag: function_test
    priority: P1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置
    run:
      -
        path: $ROOT_PATH/$model_function_path
        cmd: sh PaddleClas_CI_develop.sh ppcls/configs/ImageNet/ShuffleNet/ShuffleNetV2_x1_0.yaml

TRAIN: # 训练步骤
  -
    tag: train_linux_gpu1
    priority: P1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh grep_linux_log.sh ppcls/configs/ImageNet/ShuffleNet/ShuffleNetV2_x1_0.yaml train_linux_gpu1
    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 6.8621
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/ShuffleNetV2_x1_0_1card.log
  -
    tag: train_linux_gpu2
    priority: P1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh grep_linux_log.sh ppcls/configs/ImageNet/ShuffleNet/ShuffleNetV2_x1_0.yaml train_linux_gpu2
    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 6.65553
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/ShuffleNetV2_x1_0_2card.log

EVAL: # 训练步骤
  -
    tag: eval_linux
    priority: P1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh grep_linux_log.sh ppcls/configs/ImageNet/ShuffleNet/ShuffleNetV2_x1_0.yaml eval_linux
    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 6.65553
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/ShuffleNetV2_x1_0_eval.log

INFER: # 训练步骤
  -
    tag: infer_linux
    priority: P1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh grep_linux_log.sh ppcls/configs/ImageNet/ShuffleNet/ShuffleNetV2_x1_0.yaml infer_linux
    kpis: #kpi指标
      infer_exit_code:
        latest: True
        kpi_base: 0.0
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/ShuffleNetV2_x1_0_infer.log

PREDICT: # 训练步骤
  -
    tag: predict_linux
    priority: P1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh grep_linux_log.sh ppcls/configs/ImageNet/ShuffleNet/ShuffleNetV2_x1_0.yaml predict_linux
    kpis: #kpi指标
      predict_exit_code:
        latest: True
        kpi_base: 0.0
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/ShuffleNetV2_x1_0_predict.log
