MODEL: "realsr_kernel_noise_x4_dped" # 模型名
PRIORITY: P1_release
GIT:
  addr: $REPO_PaddleGAN
  path: $ROOT_PATH/PaddleGAN
  branch: $gan_BRANCH

ENV:
  PADDLE_ON_MODEL_CE: $PADDLE_ON_MODEL_CE

VARIABLES:
  model_function_path_linux: linux/ #脚本的路径
  model_function_path_win: windows/ #脚本的路径
  model_function_path_mac: mac/ #脚本的路径
  model_scripts_path: scripts/ #脚本的路径
  model_log_path: log

EXEC:
  exec_cases: [FUNCTION,TRAIN,EVAL]
  exec_priority: [P1_release]
  exec_tag: $EXEC_TAG

#测试套
FUNCTION: # 训练步骤
  -
    tag: linux_function_test
    priority: P1_release
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置
    run:
      -
        path: $ROOT_PATH/$model_function_path_linux
        cmd: bash PaddleGAN_CI_develop.sh configs/realsr_kernel_noise_x4_dped.yaml
  -
    tag: win_function_test
    priority: P1_release
    run:
      -
        path: $ROOT_PATH/$model_function_path_win
        cmd: PaddleGAN_train_gpu.bat configs/realsr_kernel_noise_x4_dped.yaml
  -
    tag: win_cpu_function_test
    priority: P1_release
    run:
      -
        path: $ROOT_PATH/$model_function_path_win
        cmd: PaddleGAN_train_cpu.bat configs/realsr_kernel_noise_x4_dped.yaml
  -
    tag: mac_function_test
    priority: P1_release
    run:
      -
        path: $ROOT_PATH/$model_function_path_mac
        cmd: bash PaddleGAN_train_cpu.sh configs/realsr_kernel_noise_x4_dped.yaml

TRAIN: # 训练步骤
  -
    tag: train_linux_gpu1
    priority: P1_release
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash grep_linux_log.sh configs/realsr_kernel_noise_x4_dped.yaml train_linux_gpu1
    kpis: #kpi指标
      loss_pix:
        latest: True
        kpi_base: 0.143
        threshold: 1.0
        actived: True
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/realsr_kernel_noise_x4_dped_1card.log
  -
    tag: train_linux_gpu2
    priority: P1_release
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash grep_linux_log.sh configs/realsr_kernel_noise_x4_dped.yaml train_linux_gpu2
    kpis: #kpi指标
      loss_pix:
        latest: True
        kpi_base: 0.086
        threshold: 1.0
        actived: True
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/realsr_kernel_noise_x4_dped_2card.log
  -
    tag: train_win_gpu
    priority: P1_release
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: grep_win_log.bat configs/realsr_kernel_noise_x4_dped.yaml train_win_gpu
    kpis: #kpi指标
      training_exit_code:
        latest: True
        kpi_base: 0.0
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/realsr_kernel_noise_x4_dped_train.log
  -
    tag: train_win_cpu
    priority: P1_release
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: grep_win_log.bat configs/realsr_kernel_noise_x4_dped.yaml train_win_cpu
    kpis: #kpi指标
      training_exit_code:
        latest: True
        kpi_base: 0.0
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/realsr_kernel_noise_x4_dped_train.log
  -
    tag: train_mac_cpu
    priority: P1_release
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash grep_mac_log.sh configs/realsr_kernel_noise_x4_dped.yaml train_mac_cpu
    kpis: #kpi指标
      training_exit_code:
        latest: True
        kpi_base: 0.0
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/realsr_kernel_noise_x4_dped_cpu.log

EVAL: # 训练步骤
  -
    tag: eval_linux
    priority: P1_release
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash grep_linux_log.sh configs/realsr_kernel_noise_x4_dped.yaml eval_linux
    kpis: #kpi指标
      eval_exit_code:
        latest: True
        kpi_base: 0.0
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/realsr_kernel_noise_x4_dped_eval.log
  -
    tag: eval_win
    priority: P1_release
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: grep_win_log.bat configs/realsr_kernel_noise_x4_dped.yaml eval_win
    kpis: #kpi指标
      eval_exit_code:
        latest: True
        kpi_base: 0.0
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/realsr_kernel_noise_x4_dped_eval.log
  -
    tag: eval_mac
    priority: P1_release
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash grep_mac_log.sh configs/realsr_kernel_noise_x4_dped.yaml eval_mac
    kpis: #kpi指标
      eval_exit_code:
        latest: True
        kpi_base: 0.0
        threshold: 0.0
        actived: True
        evaluation: "="
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/realsr_kernel_noise_x4_dped_eval.log
