MODEL: "realsr_bicubic_noise_x4_df2k" # 模型名
PRIORITY: P1
GIT:
  addr: $REPO_PaddleGAN
  path: $ROOT_PATH/PaddleGAN
  branch: $gan_BRANCH

ENV:
  PADDLE_ON_MODEL_CE: $PADDLE_ON_MODEL_CE

VARIABLES:
  model_scripts_path: scripts/realsr_bicubic_noise_x4_df2k/ #脚本的路径
  model_log_path: log

EXEC:
  exec_cases: [TRAIN]
  exec_priority: [P1]
  exec_tag: [linux_dy_gpu1,linux_dy_gpu2]
#测试套
TRAIN: # 训练步骤
  -
    priority: P1  # dy_gpu1
    tag: linux_dy_gpu1
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train_1card.sh

    kpis: #kpi指标
      loss_pix:
        latest: True
        kpi_base: 0.034
        threshold: 1 # 0.02
        actived: True
        evaluation: "-"
    output: $ROOT_PATH/$model_log_path/realsr_bicubic_noise_x4_df2k_1card.log
  -
    priority: P1  # dy_gpu1
    tag: linux_dy_gpu2
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_MULTI_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: sh train_2card.sh

    kpis: #kpi指标
      loss_pix:
        latest: True
        kpi_base: 0.022
        threshold: 1 # 0.02
        actived: True
        evaluation: "-"
    output: $ROOT_PATH/$model_log_path/realsr_bicubic_noise_x4_df2k_2card.log
