MODEL: "text_classification_pretrained" # 模型名
PRIORITY: P0
GIT:
  addr: $REPO_PaddleNLP
  path: $ROOT_PATH/models_repo
  branch: $BASE_BRANCH

VARIABLES:
  scripts_path: scripts
  model_scripts_path: scripts/text_classification_pretrained/ #脚本的路径
  model_log_path: log/text_classification_pretrained/

EXEC:
  exec_cases: [DATA_PROC,TRAIN,INFER, PYTHON_INFER]
  exec_priority: [p0, p1]
  exec_tag: $EXEC_TAG

#测试套
DATA_PROC:
  -
    priority: p0
    tag: linux_download_data
    run:
      -
        path: $ROOT_PATH/$scripts_path
        cmd: bash run_nlp_all_case.sh pretrained_models $XPU linux $SET_CUDA $SET_MULTI_CUDA CE

TRAIN: # 训练步骤
  -
    priority: p0
    tag: linux_dy_gpu1


    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 0.19159
        threshold: 0.05
        actived: True
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/train_single_$XPU.log

  -
    priority: p1
    tag: linux_dy_gpu2

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 0.14233
        threshold: 0.5
        actived: True
        evaluation: "-"
        unit_repr: "s"

    output: $ROOT_PATH/$model_log_path/train_multi_$XPU.log

  -
    priority: p0
    tag: "linux_dy_cpu"
    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: bash train.sh $XPU

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 0.18155
        threshold: 0.01
        actived: True
        evaluation: "-"
        unit_repr: "s"

    output: $ROOT_PATH/$model_log_path/train_$XPU.log

  -
    priority: p0
    tag: "win_dy_gpu1"
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: train.bat $XPU

    kpis: #kpi指标
      loss:
        latest: True
        kpi_base: 0.19388
        threshold: 0.05
        actived: True
        evaluation: "-"
        unit_repr: "s"
    output: $ROOT_PATH/$model_log_path/train_$XPU.log

INFER:
  -
    priority: p0
    tag: "linux_dy_gpu1"

    kpis:
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/infer_single_$XPU.log


  -
    priority: p1
    tag: "linux_dy_gpu2"

    kpis:
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/infer_multi_$XPU.log

  -
    priority: p0
    tag: "win_dy_gpu1"
    env: #去掉，自动调度
      CUDA_VISIBLE_DEVICES: $SET_CUDA  #取值为None，则不设置

    run:
      -
        path: $ROOT_PATH/$model_scripts_path
        cmd: infer.bat $XPU
    kpis:
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/infer_$XPU.log


PYTHON_INFER:
  -
    priority: p0
    tag: "linux_dy_gpu1"

    kpis:
      exit_code:
        latest: True
        kpi_base: 0
        threshold: 0
        actived: True
        evaluation: "-"
        unit_repr: None
    output: $ROOT_PATH/$model_log_path/python_infer_$XPU.log
